server:
  port: 6300
  error:
    include-stacktrace: never

spring:
  application:
    name: access-consumer
  cloud:
    consul:
    host: 192.168.0.12
    port: 8500
    failFast: false
    discovery:
      healthCheckUrl: http://192.168.0.12:6300/actuator/health
      healthCheckInterval: 15s
  kafka:
    bootstrap-servers: 54.39.28.62:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring:
          json:
            trusted:
              packages: br.com.itau.mastertech.acesso.access.api.model