server:
  port: 6000
  error:
    include-stacktrace: never

spring:
  application:
    name: client-api
  cloud:
    consul:
    host: 192.168.0.12
    port: 8500
    failFast: false
    discovery:
      healthCheckUrl: http://192.168.0.12:6002/actuator/health
      healthCheckInterval: 15s